@echo off
echo Creating virtual environment...
python -m venv env
echo Activating virtual environment...
call env\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Requirements installed successfully!
pause