@echo off
echo Launching environment...
call env\Scripts\activate.bat
echo Launching WPChanger.py...
python WPChanger.py
echo Deactivating virtual environment...
call venv\Scripts\Deactivate.bat
pause